#!/bin/bash
set -e
systemctl daemon-reload
systemctl enable\
	glitch-mint-logo-start.service\
	glitch-mint-logo-stop.service\
	glitch-mint-logo-halt.service\
	glitch-mint-logo-poweroff.service\
	glitch-mint-logo-reboot.service
