#!/bin/bash
set -e

mkdir -p /var/lib/glitch-mint-logo/
touch /var/lib/glitch-mint-logo/boot-timings

systemctl daemon-reload
systemctl enable\
	gml-start.service\
	gml-stop.service\
	gml-halt.service\
	gml-poweroff.service\
	gml-reboot.service

sudo systemctl enable $(cat /etc/glitch-mint-logo/notifier-services.list)
