#!/bin/bash
set -e
systemctl disable\
	gml-start.service\
	gml-stop.service\
	gml-halt.service\
	gml-poweroff.service\
	gml-reboot.service

sudo systemctl enable $(cat /etc/glitch-mint-logo/notifier-services.list)
