#!/bin/bash
set -e

dir=/var/lib/glitch-mint-logo

if [ -d "$dir" ]; then
	rm -f "$dir/boot-timings"
	rmdir --ignore-fail-on-non-empty "$dir"
fi

systemctl disable\
	gml-start.service\
	gml-stop.service\
	gml-halt.service\
	gml-poweroff.service\
	gml-reboot.service

sudo systemctl enable $(cat /etc/glitch-mint-logo/notifier-services.list)
